services:
  myDB:
    image: postgres:18-alpine3.23
    container_name: dss_postgres
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=dss_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
